### ISSUE TITLE
installed Fake Pkg Files dont work

### ISSUE THREAD

**Issue by aloksaurabh** [stooged/PS4_Serve3#2]
I have been using Al-azifs offline exploit host for a while
https://github.com/Al-Azif/ps4-exploit-host/releases/tag/v0.4.5 
it works as as expected. I have dumped games. I have created fake pkg files, installed them and I play them.
Now i am trying to switch to this apk. I cannot get old fake package installed games to work. It asks me to buy them. i get game debug settings. I think i can install new games as well but old installed games from fake pkg files dont work. Is it because al-azif is using a different version of hen ? or his host loads mira+hen and this loads only hen ?

**Comment by stooged** [comment]
The mira+hen you used was a buggy version of hen and it should have been removed as soon as xvortex fixed the issue and updated hen to 1.6 but alot of people left mira+hen in their public releases because they did not pay attention.

This means when you use mira+hen to install games and then run hen 1.6 or 1.7 the games remain locked.

Mira has no use for the end user until a payload utilizes it directly so using it with hen to just run games is pointless but people dont seem to understand that.

You can either reinstall your games using hen 1.7 or you will need to load the old mira+hen to run those games.

The entire problem is just an incompatibility between the 2 different hen versions unfortunately.

**Comment by aloksaurabh** [comment]
Those who have to do this, do not worry. The game saves stay
